import {logger} from '@/lib/logger'
import OpenAI from 'openai'
import {SubscriptionUsageService} from '@/services/subscription/subscription-usage-service'

const IMAGE_GENERATION_MODEL = 'google/gemini-2.5-flash-image-preview'

export interface ImageGenerationRequest {
  prompt: string
  userId: string
}

export interface ImageGenerationResponse {
  imageUrl: string
  prompt: string
}

export class ImageCreatorService {
  private static client = new OpenAI({
    apiKey: process.env.OPENROUTER_API_KEY,
    baseURL: "https://openrouter.ai/api/v1",
    defaultHeaders: {
      "HTTP-Referer": process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
      "X-Title": "MIA App",
    },
  })

  /**
   * Generate an image using AI
   */
  static async generateImage(
    userId: string,
    request: ImageGenerationRequest
  ): Promise<ImageGenerationResponse> {
    const {prompt} = request

    if (!prompt?.trim()) {
      throw new Error('Prompt is required for image generation')
    }

    try {
      // Generate the image using OpenRouter with image modalities
      const completion = await this.client.chat.completions.create({
        model: IMAGE_GENERATION_MODEL,
        messages: [
          {
            role: 'user',
            content: prompt.trim(),
          },
        ],
        temperature: 0.7, // Good balance for creative image generation
        // Include modalities for image generation as per OpenRouter docs
        modalities: ['image', 'text'] as any,
        stream: false
      })

      // Handle the response according to OpenRouter documentation
      const message = completion.choices[0]?.message
      if (!message) {
        throw new Error('No response from image generation model')
      }

      // Check for images in the response (as per OpenRouter docs)
      const images = (message as any).images
      let imageUrl: string

      if (images && Array.isArray(images) && images.length > 0) {
        const firstImage = images[0]
        if (firstImage?.image_url?.url) {
          imageUrl = firstImage.image_url.url
          logger.info('🎨 Image found in response', {
            userId,
            operation: 'image-extraction',
            metadata: {
              imageType: imageUrl.startsWith('data:') ? 'base64' : 'url',
              imageUrlPreview: imageUrl.substring(0, 100)
            }
          })
        } else {
          throw new Error('Image data not found in expected format')
        }
      } else if (message.content) {
        // Fallback: try to extract image from content if no images field
        logger.warn('No images field in response, checking content', {
          metadata: {
            contentPreview: message.content.substring(0, 200)
          }
        })
        throw new Error(`Model did not return images. Content: ${message.content.substring(0, 200)}`)
      } else {
        throw new Error('No image generated by the model')
      }

      // Track usage/cost
      const cost = (completion as any).usage?.cost
      if (cost) {
        await SubscriptionUsageService.trackCost(userId, cost)
        logger.info('🎨 Image generation cost tracked', {
          userId,
          operation: 'image-cost-tracking',
          metadata: {
            cost_usd: cost,
            model: IMAGE_GENERATION_MODEL
          }
        })
      }

      return {
        imageUrl,
        prompt
      }
    } catch (error) {
      logger.error('Image generation error', error instanceof Error ? error : new Error(String(error)), {
        metadata: {
          userId,
          model: IMAGE_GENERATION_MODEL
        }
      })
      
      throw error instanceof Error 
        ? error 
        : new Error('Failed to generate image')
    }
  }
}