-- CreateEnum
CREATE TYPE "DealCategory" AS ENUM ('CONFERENCE', 'ONLINE_COURSE', 'ONLINE_CONSULTANCY', 'GROUP_COACHING', 'COLIVING', 'COWORKING', 'RETREAT', 'HOTELS', 'MASTERMIND', 'RESTAURANT', 'TRANSPORTATION');

-- AlterTable
ALTER TABLE "deals" ADD COLUMN     "category" "DealCategory" NOT NULL DEFAULT 'COLIVING';
